#!/bin/bash -eu
# -*- mode:shell-script;coding:utf-8 -*-
#*****************************************************************************
#FILE:               install-pjb-environment
#LANGUAGE:           bash
#SYSTEM:             POSIX
#USER-INTERFACE:     NONE
#DESCRIPTION
#
#    This script fetches and installs my environment.
#
#AUTHORS
#    <PJB> Pascal J. Bourguignon <pjb@informatimago.com>
#MODIFICATIONS
#    2016-12-04 <PJB> Added this header.
#BUGS
#    - Add installation of quicklisp
#LEGAL
#    AGPL3
#
#    Copyright Pascal J. Bourguignon 2016 - 2021
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*****************************************************************************

self="$(cd "$(dirname "$0")";pwd -P)/$(basename "$0")"
# shellcheck disable=SC1090
source "${self}.bash"


function usage(){
    local pname="$1"
    printf '%s usage:\n\n' "${pname}"
    printf '    %s [option]\n\n' "${pname}"
    printf 'option can be one of:\n'
    printf '    --only-packages       Installs only linux packages.\n'
    printf '    --install-ports       Installs only MacPorts packages.\n'
    printf '    --only-local          Installs only /usr/local stuff.\n'
    printf '    --from-sources=<name> Compiles package <name> from sources.\n'
    printf '        package can be one of: emacs ccl clisp abcl ecl emacs_w3m\n'
    printf '\n'
}


function main(){
    for arg ; do
	    case "${arg}" in
        (--headless)
			# shellcheck disable=SC2034
            headless=1
            ;;
	    (--install-ports)
		    install_ports
		    exit 0
		    ;;
        (--only-packages)
            prerequisites
            install_packages
            exit 0
            ;;
        (--only-local)
            prerequisites
            install_usr_local_stuff
            exit 0
            ;;
        (--from-sources=*)
            name="${arg/--from-sources=/}"
            fun=install_${name}_from_sources
            if [ "$(type -t "$fun")" = function ] ; then
                "$fun"
                exit 0
            fi
            printf 'Unknown package: %s\n' "$name"
		    usage "$(basename "$0")"
            exit 1
            ;;
	    (*)
		    printf 'Invalid option %s\n' "${arg}"
		    usage "$(basename "$0")"
		    exit 1
		    ;;
	    esac
    done
    prerequisites
    install_all
    exit 0
}

main "$@"
